In [7]:
#Converta os elementos do array [3, 5, 9, 16, 25] para float.
array_inteiros = [3, 5, 9, 16, 25]

array_floats = [float(elemento) for elemento in array_inteiros]

print(array_floats)

[3.0, 5.0, 9.0, 16.0, 25.0]


In [11]:
#Dado o array [1.2, -3.6, 8.99999, 16.1], converta os seus elementos para int.

array_floats = [1.2, -3.6, 8.99999, 16.1]

array_inteiros = [int(elemento) for elemento in array_floats]

print(array_inteiros)

[1, -3, 8, 16]


In [15]:
#Crie uma matriz 3x9 contendo apenas elementos com valor zero.

import numpy as np

matriz_zeros = np.zeros((3, 9))

print(matriz_zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
