In [7]:
#Converta os elementos do array [3, 5, 9, 16, 25] para float.

array_inteiros = [3, 5, 9, 16, 25]

array_floats = [float(elemento) for elemento in array_inteiros]

print(array_floats)

[3.0, 5.0, 9.0, 16.0, 25.0]


In [11]:
#Dado o array [1.2, -3.6, 8.99999, 16.1], converta os seus elementos para int.

array_floats = [1.2, -3.6, 8.99999, 16.1]

array_inteiros = [int(elemento) for elemento in array_floats]

print(array_inteiros)

[1, -3, 8, 16]


In [7]:
#Crie uma matriz 3x9 contendo apenas elementos com valor zero.

import numpy as np

matriz_zeros = np.zeros((3, 9))

print(matriz_zeros)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
#Crie uma matriz 6x7 de números inteiros contendo elementos com valor 1.

import numpy as np

matriz = np.ones((6, 7), dtype=int)

print(matriz)

[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


In [9]:
#Crie uma matriz identidade de tamanho 4.

import numpy as np

matriz_identidade = np.eye(4)

print(matriz_identidade)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
#Crie um array de números aleatórios entre 0 e 1 de tamanho 5.

import numpy as np

array_aleatorio = np.random.rand(5)

print(array_aleatorio)

[0.58483203 0.45744499 0.73034963 0.33104352 0.32065415]


In [19]:
#Crie uma matriz 3x6 contendo números aleatórios de 0 a 5 (0, 1, 2, 3, 4, 5).

import numpy as np

matriz_randomica = np.random.randint(0, 6, size=(3, 6))

print(matriz_randomica)

[[3 1 0 5 2 2]
 [5 4 4 0 4 0]
 [3 5 2 1 4 4]]


In [21]:
#Informe o código para exibir o valor máximo da matriz.

import numpy as np

matriz_exemplo = np.array([[4, 6, 8],
                           [-4, 3, 2],
                           [22, -15, 12]])

valor_maximo = np.max(matriz_exemplo)

print("O valor máximo da matriz é:", valor_maximo)

O valor máximo da matriz é: 22


In [23]:
#Qual o código para exibir o valor mínimo da matriz?

import numpy as np

matriz_exemplo = np.array([[4, 6, 8],
                           [-4, 3, 2],
                           [22, -15, 12]])

valor_minimo = np.min(matriz_exemplo)

print("O valor mínimo da matriz é:", valor_minimo)

O valor mínimo da matriz é: -15


In [25]:
#Como fazer para imprimir na tela a soma dos elementos da matriz?

import numpy as np

matriz_exemplo = np.array([[4, 6, 8],
                           [-4, 3, 2],
                           [22, -15, 12]])

media = np.mean(matriz)

# Exibe a média
print("A média dos elementos da matriz é:", media)

A média dos elementos da matriz é: 1.0


In [29]:
#Exibir o 4º elemento do array.

array = [13, -2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12]

print("O 4º elemento do array é:", array[3])

O 4º elemento do array é: 8


In [31]:
#Exibir os 3 últimos elementos do array.

array = [13, -2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12]

print("Os 3 últimos elementos do array são:", array[-3:])

Os 3 últimos elementos do array são: [10, 56, 12]


In [37]:
#Exibir os elementos a partir da posição 2.

array = [13, -2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12]

print("Os elementos a partir da posição 2 são:", array[1:])

Os elementos a partir da posição 2 são: [-2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12]


In [39]:
#Exibir um array entre o 2º e o 6º elementos. O 6º elemento deve estar presente.

array = [13, -2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12]

print("O subarray entre o 2º e o 6º elementos é:", array[1:6])

O subarray entre o 2º e o 6º elementos é: [-2, 6, 8, 23, 15]


In [43]:
#Escreva o código que resulta na exibição do seguinte array: [23 15 3 90] 

array = [13, -2, 6, 8, 23, 15, 3, 90, 4, 10, 56, 12]

print("O array desejado é:", array[4:8])

O array desejado é: [23, 15, 3, 90]


In [52]:
#Escreva o código para exibir a 3ª linha da matriz.

import numpy as np

matriz = np.array([
    [1, 3, 16, -25, 14],
    [2, 0, 10, 5, 17],
    [19, 4, 8, 15, 13],
    [7, 12, -5, 14, 0]
])

terceira_linha = matriz[2]

print("A 3ª linha da matriz é:", terceira_linha)

A 3ª linha da matriz é: [19  4  8 15 13]


In [54]:
#Escreva o código para exibir a 4ª coluna

import numpy as np

matriz = np.array([
    [1, 3, 16, -25, 14],
    [2, 0, 10, 5, 17],
    [19, 4, 8, 15, 13],
    [7, 12, -5, 14, 0]
])

quarta_coluna = matriz[:, 3]

print("A 4ª coluna da matriz é:", quarta_coluna)

A 4ª coluna da matriz é: [-25   5  15  14]


In [63]:
#Escreva o código para exibir o elemento de valor 10.

import numpy as np

matriz = np.array([
    [1, 3, 16, -25, 14],
    [2, 0, 10, 5, 17],
    [19, 4, 8, 15, 13],
    [7, 12, -5, 14, 0]
])

print("O elemento de valor:", matriz[1, 2])

O elemento de valor: 10


In [65]:
#Escreva o código que resulta na seguinte matriz:[[0	10	5] [4	8	15]]

import numpy as np

matriz_original = np.array([
    [1, 3, 16, -25, 14],
    [2, 0, 10, 5, 17],
    [19, 4, 8, 15, 13],
    [7, 12, -5, 14, 0]
])

matriz_resultante = matriz_original[1:3, 1:4]

print("A matriz resultante é:")
print(matriz_resultante)

A matriz resultante é:
[[ 0 10  5]
 [ 4  8 15]]


In [69]:
#Crie uma nova matriz, atribuindo o valor 1 para os números ímpares, e 2, para os números pares, utilizando a biblioteca numpy.

import numpy as np

matriz = np.array([
    [2, -1, 15, 24],
    [-3, 18, 4, 25],
    [9, 10, -13, 7]
])

nova_matriz = np.where(matriz % 2 == 0, 2, 1)

print("A nova matriz é:")
print(nova_matriz)

A nova matriz é:
[[2 1 1 2]
 [1 2 2 1]
 [1 2 1 1]]
